Gestion_Produits/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Gestion_Produits import settings
from gestion_prod.views import cart, product_detail


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion_prod/',include('gestion_prod.urls',namespace='gestion_prod')),
    path("accounts/", include("accounts.urls",namespace="accounts")),
    path('cart/',cart, name='cart'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name='accounts'


urlpatterns=[
    path('login/', views.login_view,name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.register_view, name='signup')    
]

gestion_prod/urls.py
from django.urls import path

from gestion_prod import views
app_name='gestion_prod'

urlpatterns=[
    path('',views.list_prod, name='list_prod'),    
    path('<slug:product>/',views.product_detail,name='product_detail'),
    path('<str:slug>/add_to_cart',views.add_to_cart,name='add_to_cart'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User (AbstractUser):
    ROLES=(
        ('user','user'),
        ('admin','admin')
    )

    #unique email
    email=models.EmailField(unique=True)

    role=models.CharField(max_length=30,choices=ROLES,default='user')

    description=models.TextField(blank=True, default='')

    def __str__(self):
        return self.username

gestion_prod/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from Gestion_Produits.settings import AUTH_USER_MODEL
from accounts.models import User


# Create your models here.
class Categorie(models.Model):
    name=models.CharField(max_length=100)
    def __str__(self) :
            return self.name

class StockedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(stock__gt=0)
        
class Product(models.Model):
    name=models.CharField(max_length=100)
    slug=models.SlugField(max_length=250)
    stock=models.IntegerField(default=0)
    price=models.DecimalField(max_digits=6,decimal_places=2)
    description=models.TextField(default="",blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    thembnail=models.ImageField(upload_to="products_img", blank=True, null=True)
    objects=models.Manager()
    author=models.ForeignKey(User, on_delete=models.CASCADE, related_name='products_user')
    category = models.ForeignKey(Categorie, on_delete=models.CASCADE, related_name='products')
    InStock=StockedManager()
    def get_absolute_url (self):
        return reverse('gestion_prod:product_detail', 
                       args=[self.slug])
    class Meta:
        ordering = ['-price']
        indexes=[models.Index(fields=['-stock'])]   
        def __str__(self) :
            return self.name

class Ordre(models.Model):
    user= models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    quantite= models.IntegerField(default=1)
    ordred= models.BooleanField(default=False)

    def __str__(self):
         return f"{self.product.name} ({self.quantite})"
     
class Cart(models.Model):
     user = models.OneToOneField(AUTH_USER_MODEL,on_delete=models.CASCADE)
     orders = models.ManyToManyField(Ordre)
     ordered = models.BooleanField(default=False)
     ordered_date= models.DateTimeField(blank=True, null=True)
     def __str__(self):
         return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserRegistrationForm(UserCreationForm):
    email=forms.EmailField(help_text='a valid email please', required=True)

    class Meta:
        model= get_user_model()
        fields=['first_name', 'last_name', 'username', 'email', 'password1','password2']

    def save(self,commit=True):
        user=super(UserRegistrationForm,self).save(commit=False)
        user.email=self.cleaned_data['email']
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import UserRegistrationForm



# Create your views here.
def register_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('gestion_prod:list_prod'))

    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('gestion_prod:list_prod'))
        
    else:
        form = UserRegistrationForm()

    return render(
        request=request,
        template_name = "registration/signup.html",
        context={"form": form}
    )

def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('gestion_prod:list_prod'))

    if request.method == "POST":
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)                       
                return redirect(reverse('gestion_prod:list_prod'))
            
    form = AuthenticationForm()

    return render(
        request=request,
        template_name="registration/login.html",
        context={"form": form}
        )
            
@login_required
def logout_view(request):
    logout(request)    
    return redirect(reverse('gestion_prod:list_prod'))

gestion_prod/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from gestion_prod.models import Product

# Create your views here.
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from gestion_prod.models import Cart, Ordre, Product

# Create your views here.
def list_prod(request):
    list_prod = Product.InStock.all()
    paginator = Paginator(list_prod, 3)
    page_number = request.GET.get('page', 1)
    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'gestion_prod/product/list.html', {'products': list_prod})

def product_detail(request, product):
    product=get_object_or_404(Product,slug=product)
    return render(request,'gestion_prod/product/detail.html',{"product":product})

def add_to_cart(request, slug):
    user = request.user
    product = get_object_or_404(Product, slug=slug)
    cart, _ =Cart.objects.get_or_create(user=user)
    ordre, created = Ordre.objects.get_or_create(user=user,
                                                  product=product)
    if created:
        cart.orders.add(ordre)
        cart.save()
    else:
        ordre.quantite += 1
        ordre.save()
    return redirect('gestion_prod:list_prod')

def cart(request):
    cart = get_object_or_404(Cart, user=request.user)
    return render(request, 'gestion_prod/product/cart.html', {"orders": cart.orders.all()})

gestion_prod/templates/gestion_prod/base.html
{% load products_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/gestion_prod.css' %}">
</head>
<body>
    <header>
         <nav>
            <div class="nav-wrapper">
            <a href="#" class="brand-logo">E-commerce</a>
            <ul id="" class="right hide-on-med-and-down">
                <li><a href="{% url 'gestion_prod:list_prod' %}">Products</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'cart' %}">Cart</a></li>
                
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li> Hi {{ user.username }}!
                {% else %}
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                {% endif %}
            </ul>
            </div>
        </nav>
    </header>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    {% if user.is_authenticated %}
    <div id="sidebar">
        <h2>My Products</h2>
        <p>This is my products.</p>
        I've written {% total_products %} products so far.
        <h3>latest_products</h3>
        {% show_latest_products 3 %}
    </div>
    {% endif %}
</body>
</html> 

gestion_prod/templates/gestion_prod/product/cart.html
<!-- Your HTML file -->
{% extends "gestion_prod/base.html" %}
{% block content %}
<div class="ma">
    <h1>My Cart</h1>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Product Image</th>
            <th>Product Name</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
            <tr>
                <td><img src ="{{order.product.thembnail.url}}" alt ="{{ order.product.name }}"></td>
                <td>{{ order.product.name }}</td>
                <td>{{ order.quantite }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

gestion_prod/templates/gestion_prod/product/detail.html
{% extends "gestion_prod/base.html" %}
{% block title %}Product Details{% endblock %}
{% block content %}
    <h1 class="ma">Product Details</h1>
    <div class="cadre">
        <div class="texte">
            <div class="titre-cadre">
                <h2>{{ product.name }}</h2>
            </div>
            <div class="details-cadre">
                <h3>Price : {{ product.price }}</h3>
                <h3>Stock : {{ product.stock }}</h3>
                <p>{{ product.description }}</p>
                {% if user.is_authenticated %}
                    <p>
                        <a href="{% url 'gestion_prod:add_to_cart' product.slug %}">
                            Add to cart
                        </a>
                    </p>
                {% endif %}
            </div>
        </div>
         <img src="{{ product.thembnail.url }}" alt="{{ product.name }}">
    </div>
{% endblock %}

gestion_prod/templates/gestion_prod/product/index.html
{% extends "gestion_prod/base.html" %}

gestion_prod/templates/gestion_prod/product/latest_posts.html
<ul>
    {% for product in latest_products %}
    <li>
        <a href="{{ product.get_absolute_url }}">
            {{ product.name }}
        </a>
    </li>
    {% endfor %}
</ul>

gestion_prod/templates/gestion_prod/product/list.html
{% extends "gestion_prod/base.html" %}

{% block title %}My Products{% endblock %}

{% block content %}
<h1 class="ma">All Products</h1>
<div class="card-container">
    {% for product in products %}
        <div class="card">
            <img class ="card-img-top" src="{{ product.thembnail.url }}" alt="{{ product.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <div class="card-info">
                    <p class="card-text">Price: {{ product.price }} Dt</p>
                    <p class="card-text">Stock: {{ product.stock }}</p>
                </div>
                <a href="{{ product.get_absolute_url }}" class="card-link">details</a>
            </div>
        </div>
    {% endfor %}
</div>
{% include "pagination.html" with page=products %}
{% endblock %}

gestion_prod/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">Next</a>
            {% endif %}
        </span>
    </div>